default: clean-bin build

clean-bin:
    rm -fRd ../android/app/src/main/jniLibs/*

gen:
    flutter_rust_bridge_codegen generate --config-file ../flutter_rust_bridge.yaml --enable-lifetime

build:
    cargo ndk -t armeabi-v7a,arm64-v8a,x86_64 -o ../android/app/src/main/jniLibs build --release
